### PR TITLE
Update to FIPS dev build, simplify set of Dockerfiles for the dev branch, add Mariner

### PR DESCRIPTION
**Pull request by dagood**
* Part of https://github.com/microsoft/go/issues/268

This PR updates the freshly created `dev/official/go1.17-openssl-fips` branch in microsoft/go-images to create images based on an official build from `dev/official/go1.17-openssl-fips` in microsoft/go.

To keep this dev branch build simpler and avoid creating *too* many irrelevant images, I removed all versions except 1.17 and all Windows images.

Added Mariner Dockerfile generation based on the packages listed in https://github.com/microsoft/go/pull/279. Upstream only produces builds for Linux distros that use `dpkg`/`deb`, so I had to add some branching in the Dockerfile template for Mariner. The template is written in `jq`: https://stedolan.github.io/jq/manual/.

In the future, we might be better off duplicating the upstream template rather than trying to add branches and modify it in-place. Getting merge conflicts would let us make sure our Mariner images are up to date with how upstream builds its Debian images, but Git merge conflict detection also causes a *lot* of false positives, and it might not be worth it.

<details><summary>

~~I wasn't able to quite get the images working. Testing out the Mariner image with FIPS mode (click me):~~ The images are working now, see comment thread.

</summary>

```
root [ /go ]# go tool dist test -run crypto/internal

##### Testing packages.
ok      crypto/internal/boring  0.002s
ok      crypto/internal/subtle  0.001s

ALL TESTS PASSED (some were excluded)
```

```
root [ /go ]# export GOLANG_FIPS=1
root [ /go ]# go tool dist test -run crypto/internal
panic: boringcrypto: OpenSSL dlopen failed

goroutine 1 [running]:
crypto/internal/boring.init.0()
        /usr/local/go/src/crypto/internal/boring/boring.go:42 +0x165
root [ /go ]# export GO_OPENSSL_VERSION_OVERRIDE=1234
root [ /go ]# go tool dist test -run crypto/internal
panic: boringcrypto: OpenSSL dlopen failed

goroutine 1 [running]:
crypto/internal/boring.init.0()
        /usr/local/go/src/crypto/internal/boring/boring.go:42 +0x165
```

```
root [ /go ]# export GOLANG_FIPS=1
root [ /go ]# export GO_OPENSSL_VERSION_OVERRIDE=1.1
root [ /go ]# go tool dist test -run crypto/internal
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0x9c99c1, 0xa92598})
        /usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x401a30, 0xc0000bb7f8)
        /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0000bb7d0 sp=0xc0000bb798 pc=0x409bbc
crypto/internal/boring._Cfunc__goboringcrypto_OPENSSL_setup()
        _cgo_gotypes.go:1546 +0x48 fp=0xc0000bb7f8 sp=0xc0000bb7d0 pc=0x5e0b28
crypto/internal/boring.init.0()
        /usr/local/go/src/crypto/internal/boring/boring.go:45 +0xaf fp=0xc0000bb830 sp=0xc0000bb7f8 pc=0x5e4a6f
runtime.doInit(0xd62e20)
        /usr/local/go/src/runtime/proc.go:6498 +0x123 fp=0xc0000bb968 sp=0xc0000bb830 pc=0x449843
runtime.doInit(0xd60700)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc0000bbaa0 sp=0xc0000bb968 pc=0x449791
runtime.doInit(0xd642a0)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc0000bbbd8 sp=0xc0000bbaa0 pc=0x449791
runtime.doInit(0xd64360)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc0000bbd10 sp=0xc0000bbbd8 pc=0x449791
runtime.doInit(0xd63640)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc0000bbe48 sp=0xc0000bbd10 pc=0x449791
runtime.doInit(0xd65ee0)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc0000bbf80 sp=0xc0000bbe48 pc=0x449791
runtime.main()
        /usr/local/go/src/runtime/proc.go:238 +0x1e6 fp=0xc0000bbfe0 sp=0xc0000bbf80 pc=0x43c686
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000bbfe8 sp=0xc0000bbfe0 pc=0x46a181
```

</summary>

### CODE REVIEW

**Comment by dagood** [comment]
@qmuntal can you give it a shot and let me know if something obvious is missing causing my `go tool dist test [...]` attempt to fail? (To try it out locally without infra getting in the way, you can just build the Dockerfile from `src/microsoft/1.17/cbl-mariner1.0.20211027` directly without the build scripts.)

**Comment by qmuntal** [comment]
@dagood `https://dotnetbuildoutput.blob.core.windows.net/golang/microsoft/dev/official/go1.17-openssl-fips/20211117.1/go.20211117.1.linux-amd64.tar.gz` was built using an ubuntu image that contained openssl v1.0.2 and Mariner uses openssl v1.1.1. Both versions are incompatible (openssl was not following semver at that point) and we don't support yet using a openssl version that is incompatible with the one used to build the toolchain. So go will try to dload any of this versions libcrypto.so.[1.0.2,1.0.0,10] and it will fail as these fails do not exist in Mariner.

This are the command I used to check the go openssl version vs the system installed one:

```bash
docker build -t go-mariner ./src/microsoft/1.17/cbl-mariner1.0.20211027
docker run -it -e "GOLANG_FIPS=1" go-mariner bash
```
Inside the container, first check which libcrypto libraries are available:
```bash
root [ /go ]# ls /usr/lib/libcrypto.*
/usr/lib/libcrypto.so  /usr/lib/libcrypto.so.1.1  /usr/lib/libcrypto.so.1.1.1k
```
Then check which libcrypto libraries are known by the go toolchain:
```bash
root [ /go ]# strings /usr/local/go/pkg/linux_amd64/crypto/internal/boring.a | grep libcrypto
libcrypto.so.1.0.2
libcrypto.so.1.0.0
libcrypto.so.10
libcrypto.so.
```

**Comment by qmuntal** [comment]
I see two solutions:
- Build go toolchain from scratch inside Mariner
- Invest probably 1 week in implementing the openssl bindings in a way that the openssl version is not fixed at build time

I will create an issue in microsoft/go for the second option, to keep it tracked even if we choose the first one here.

**Comment by dagood** [comment]
Another option, although I'm not sure how well it works in the Go ecosystem:

* Add a new GOOS called `cblmariner1.0.20211027` and add that OS to our build matrix in microsoft/go.

The reason this makes sense to me is it matches reality: we are building a copy of Go that only works on that distro due to the direct OpenSSL compatibility requirement. When you grab a FIPS branch build of Go toolset that calls itself "linux", it may or may not work on another Linux system, so being more specific with GOOS seems reasonable.

A quirk is that we aren't able to cross-build from one GOOS to another, because to build for a target GOOS, you need to build (and link?) against that OS's version of OpenSSL, which almost definitely isn't on the current system. But, using a differentiated GOOS value gives us an opportunity to make this clear: when someone attempts to do a cross-OS build, we can show a "you can't do that!" error message that describes why.

.NET stores all the possible OSes in a graph (for fallbacks based on OS classification), so adding a specialized OS value isn't a big deal there, but I'm not sure if Go has something similar.

---

> Then check which libcrypto libraries are known by the go toolchain:
> 
> ```shell
> root [ /go ]# strings /usr/local/go/pkg/linux_amd64/crypto/internal/boring.a | grep libcrypto
> libcrypto.so.1.0.2
> libcrypto.so.1.0.0
> libcrypto.so.10
> libcrypto.so.
> ```

That's interesting, and good tip. I didn't realize that `boring.a` was being precompiled and actually used at build-time. I expected that maybe even though it's pre-compiled, `go build` would be able to build the user's app using the source code to support other `libcrypto` versions. (Whatever `libcrypto` is specified in the user's OpenSSL headers.)

It looks like if we get `go` to rebuild the standard library, it actually works more like I expected. A test with a program that runs `sha256.Sum256`:

```shell
# go build main.go
# ./main
[143 67 67 70 100 143 107 150 223 137 221 169 1 197 23 107 16 166 216 57 97 221 60 26 200 139 89 178 220 50 122 164]
# GOLANG_FIPS=1 ./main
panic: boringcrypto: OpenSSL dlopen failed [...]
# rm $(go env GOROOT)/pkg/linux_amd64/crypto/internal/boring.a
# go build main.go
# GOLANG_FIPS=1 ./main
[143 67 67 70 100 143 107 150 223 137 221 169 1 197 23 107 16 166 216 57 97 221 60 26 200 139 89 178 220 50 122 164]
```

Maybe adding a step to the Dockerfile to rebuild this package might be a reasonable workaround without going as far as building the entire toolset from source during the Docker image builds.

---

That all said, this would be far better if we can manage it:
 
> * Invest probably 1 week in implementing the openssl bindings in a way that the openssl version is not fixed at build time

It seems like it would not only solve this new (to me) Go toolset usage issue, but also the cross-OS build issues we've had in mind. (The Microsoft build of .NET needs to do it this way because you're able to build a self-contained .NET app for "linux" and run it on linux machines with various OpenSSL versions.)

I think it's relatively common to build in one Docker container and then ship or use binaries in a different Docker container. (E.g. multi-stage Dockerfile builds: use a capable distro to build your microservice app binary, then put the binary in a minimal distro to actually deploy.) So I think the cross-OS build issue would come up a lot if we don't go with the portable approach.

**Comment by qmuntal** [comment]
> Add a new GOOS called cblmariner1.0.20211027 and add that OS to our build matrix in microsoft/go.

`openssl` is taken from the package manager, not preinstalled in the OS, so even it could be that someone is using `cblmariner1.0.20211027` with openssl 1.1.1 now but openssl 3.0 in 6 month. Adding a new GOOS also implies changing a lot of file names and build tags across all the tree, so I would leave it as the very last option.

> I didn't realize that boring.a was being precompiled and actually used at build-time.

Neither did I until I started investigating this issue 😄 

> It looks like if we get go to rebuild the standard library, it actually works more like I expected. A test with a program that runs sha256.Sum256

That's clever! I think it can easily be done by running `go tool bootstrap` after downloading and unpacking the tar ball. This would solve the problem short term, but I buy your arguments in favor of allowing to use openssl in _portable_ mode. In fact today I've been prototyping this change, and I don't think its that difficult to implement nor to maintain.

**Comment by dagood** [comment]
> `openssl` is taken from the package manager, not preinstalled in the OS, so even it could be that someone is using `cblmariner1.0.20211027` with openssl 1.1.1 now but openssl 3.0 in 6 month.

True, and there's a lot of diversity in how distros maintain multiple versions in their repositories for compatibility reasons, and do/don't remove old versions from their repositories. Not sure where Mariner falls in that spectrum. But yes, not worth digging into too far--doesn't seem like a tenable approach, anyway.

> I think [the rebuild] can easily be done by running `go tool bootstrap` after downloading and unpacking the tar ball.

Sounds like `go tool dist bootstrap` is what you meant, but I'm not actually sure how to make it work: if I run it in `GOROOT/src` like it seems you're supposed to, it fails to find `/root/go1.4`. But, maybe it's overkill? IIRC that tool is meant for bootstrapping from the C++-based Go for situations where you can't use existing Go binaries.

I *think* all we need is `go install -a crypto/internal/boring`. (I happened to remember this is similar to [how the race detector is built](https://github.com/microsoft/go/blob/677e5616087628d08d1a582ae60f0b34028c27d7/eng/_core/cmd/build/build.go#L122).)   Seems to work after checking it out with `strings`--I'll try it as a Dockerfile step and add it to the PR.

**Comment by dagood** [comment]
> I _think_ all we need is `go install -a crypto/internal/boring`

I included `cmd` too, so you can run `go build`, `go run` etc. in FIPS mode too, to keep things simple.

**Comment by dagood** [comment]
@microsoft/golang-compiler PTAL.

This is the initial PR on a dev branch that will build the FIPS-enabled-Go Docker images. This adds a `dev-fips-` prefix to the tag names to differentiate from the `microsoft/main` branch, so images will be accessible like this once this is merged and gets built:

```
mcr.microsoft.com/oss/go/microsoft/alpha/golang:dev-fips-latest
mcr.microsoft.com/oss/go/microsoft/alpha/golang:dev-fips-1.17
mcr.microsoft.com/oss/go/microsoft/alpha/golang:dev-fips-1.17.2-1-cbl-mariner1.0.20211027
...
```

The Debian images don't work in FIPS mode, but by default they use Golang's crypto and should still work for other scenarios. We can use these to validate that things will go ok for anyone running non-FIPS Go on non-FIPS distros. That way we can be relatively sure we won't break anyone if we ship FIPS-compatible Go as the only version to consolidate our branches.

```
mcr.microsoft.com/oss/go/microsoft/alpha/golang:dev-fips-1.17.2-bullseye
```

**Comment by jaredpar** [comment]
> I didn't realize that boring.a was being precompiled and actually used at build-time.

Believe this is due to the fact that FIPS is a binary certification, not a source one. Hence the only way for boring to be FIPS compatible is for them to re-dist a binary here that is compiled as specified in their FIPS certification documents.
- https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2964.pdf
- https://csrc.nist.gov/projects/cryptographic-module-validation-program/Certificate/3318
- https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3678.pdf

**Comment by dagood** [comment]
> Believe this is due to the fact that FIPS is a binary certification, not a source one. Hence the only way for boring to be FIPS compatible is for them to re-dist a binary here that is compiled as specified in their FIPS certification documents.

I think that applies to the crypto engine itself, which is even checked in as prebuilt (https://github.com/golang/go/blob/dev.boringcrypto.go1.17/src/crypto/internal/boring/goboringcrypto_linux_amd64.syso), but we're just talking about the standard library. It's normal for any Go toolset distribution to include a completely prebuilt standard library, I just wasn't familiar with when that prebuilt standard lib is used. (Basically: that the prebuilt binaries include Cgo bits.)

**Comment by dagood** [comment]
@qmuntal @chsienki @jaredpar can you give this a review?

**Review by qmuntal — APPROVED** [review]

**Review by chsienki — APPROVED** [review]

**Comment by dagood** [comment]
Thanks!

**Pull request merged**
