### PR TITLE
Update dependencies in `dev/official/go1.17-openssl-fips`

### PR DESCRIPTION
**Pull request by ghost**
🔃 This is an automatically generated PR updating the version of Go in `dev/official/go1.17-openssl-fips`.

This PR should auto-merge itself when PR validation passes.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Thanks! Auto-approving.

**Comment by dagood** [comment]
Hmm, a lot of multiple definition errors like this on bullseye (Debian 11) but not buster (Debian 10) when we rebuild crypto/internal/boring and cmd inside the container:

```
+ /usr/local/go/bin/go install -a crypto/internal/boring cmd
# crypto/internal/boring
/usr/bin/ld: $WORK/b001/_x003.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: multiple definition of `_g_BN_bin2bn'; $WORK/b001/_x002.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: first defined here
/usr/bin/ld: $WORK/b001/_x003.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: multiple definition of `_g_BN_bn2bin'; $WORK/b001/_x002.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: first defined here
/usr/bin/ld: $WORK/b001/_x003.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: multiple definition of `_g_BN_free'; $WORK/b001/_x002.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: first defined here
/usr/bin/ld: $WORK/b001/_x003.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: multiple definition of `_g_internal_BN_num_bits'; $WORK/b001/_x002.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: first defined here
[...]
```

We can remove the container-specific rebuild because now we have a portable build, but this seems pretty strange. @qmuntal maybe you can take a look?

**Comment by qmuntal** [comment]
> Hmm, a lot of multiple definition errors like this on bullseye (Debian 11) but not buster (Debian 10) when we rebuild crypto/internal/boring and cmd inside the container:
> 
> ```
> + /usr/local/go/bin/go install -a crypto/internal/boring cmd
> # crypto/internal/boring
> /usr/bin/ld: $WORK/b001/_x003.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: multiple definition of `_g_BN_bin2bn'; $WORK/b001/_x002.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: first defined here
> /usr/bin/ld: $WORK/b001/_x003.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: multiple definition of `_g_BN_bn2bin'; $WORK/b001/_x002.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: first defined here
> /usr/bin/ld: $WORK/b001/_x003.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: multiple definition of `_g_BN_free'; $WORK/b001/_x002.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: first defined here
> /usr/bin/ld: $WORK/b001/_x003.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: multiple definition of `_g_internal_BN_num_bits'; $WORK/b001/_x002.o:/usr/local/go/src/crypto/internal/boring/goopenssl.h:113: first defined here
> [...]
> ```
> 
> We can remove the container-specific rebuild because now we have a portable build, but this seems pretty strange. @qmuntal maybe you can take a look?

Should be fixed by https://github.com/microsoft/go/pull/326

**Comment by dagood** [comment]
Enabling auto-merge hit an error, merging manually:

* https://github.com/microsoft/go/issues/344

**Pull request merged**
